name: Deploy to Cloud Run

on:
  push:
    branches:
    - main
    - feature/gitdeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Maven cache
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # validate SA
      - name: Debug GCP key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > sa-key.json
          jq . sa-key.json
      # Step 3: Authenticate to GCP using JSON key
      - name: Set up GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 4: Build & push Docker image
      - name: Build & push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/workwithgcpterraform

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy workwithgcpterraform \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/workwithgcpterraform \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
