name: Deploy to Cloud Run

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
      - feature/gitdeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      # ✅ GCP authentication using Workload Identity
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      # ✅ Install Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ✅ Build & Push Docker image
      - name: Build & Push Docker Image to Cloud Build
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/workwithgcpterraform \
            --no-source

      # ✅ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy workwithgcpterraform \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/workwithgcpterraform \
            --region europe-west1 \
            --allow-unauthenticated
